### ISSUE TITLE
Failing test.

### ISSUE THREAD

**Issue by bostrt** [bostrt/wordcount.js#3]
<pre>
  1) WordCount longest should find longest lines:
     AssertionError: 26 == 25
      at Context.<anonymous> (/home/robert/code/js/wordcount.js/test/index.js:20:13)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:221:32)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:378:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:456:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:303:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:313:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:251:23)
      at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:280:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
</pre>

**Comment by bostrt** [comment]
Looking into this ASAP.

**Comment by bostrt** [comment]
Scratch, issue was due to a bad merge by git when I pulled new changes down. I just tried getting a fresh checkout and tests pass.
